import { UserProfile, LearningRequest, LearningSession, ResourceItem, CommunityPost } from '../types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-ojaswitha',
    email: 'ojaswithasreen@gmail.com',
    fullName: 'Ojaswitha',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    college: 'UC Berkeley',
    course: 'CSE • AI/ML',
    year: '2nd Year (Sophomore)',
    location: 'Berkeley, CA',
    bio: 'Passionate about algorithms, system design, and AI models. Always learning and helping peers.',
    mode: 'both',
    activeMode: 'learner',
    isOnboarded: true,
    preferredLanguage: 'English',
    learningFormat: 'Visual & Hands-on',
    skillsToLearn: [
      {
        id: 's-python',
        name: 'Python',
        level: 'Intermediate',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Skill Assessment Passed',
        yearsOrMonthsExperience: '1 year',
      },
      {
        id: 's-webdev',
        name: 'Web Development',
        level: 'Intermediate',
        category: 'Programming',
        verified: true,
      },
      {
        id: 's-dsa',
        name: 'Data Structures & Algorithms',
        level: 'Beginner',
        category: 'Programming',
        verified: false,
      },
    ],
    skillsToTeach: [
      {
        id: 's-uiux',
        name: 'UI/UX Design',
        level: 'Advanced',
        category: 'Design',
        verified: true,
        verifiedMethod: 'Project Verified',
        endorsementsCount: 18,
        yearsOrMonthsExperience: '2 years',
      },
      {
        id: 's-html-css',
        name: 'HTML/CSS',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Project Verified',
        endorsementsCount: 14,
        yearsOrMonthsExperience: '2 years',
      },
    ],
    learningGoals: [
      {
        id: 'g-1',
        skill: 'Python',
        targetTopic: 'Master nested loops and list comprehensions',
        progressPercent: 68,
        status: 'in_progress',
      },
      {
        id: 'g-2',
        skill: 'Web Development',
        targetTopic: 'Modern Full-Stack Architecture & APIs',
        progressPercent: 60,
        status: 'in_progress',
      },
    ],
    availability: {
      status: 'available',
      days: ['Mon', 'Wed', 'Fri', 'Sat'],
      timeSlots: ['4:00 PM - 7:00 PM', '8:00 PM - 10:00 PM'],
      preferredDurationMinutes: 20,
    },
    reputation: {
      score: 96,
      learnersHelped: 23,
      sessionsCount: 18,
      averageRating: 4.8,
      clarityScore: 95,
      accuracyScore: 96,
      consistencyScore: 94,
      badges: [
        {
          id: 'b-rising',
          name: 'Rising Mentor',
          description: 'Maintained 4.8+ rating across first 10 peer teaching sessions',
          icon: 'Sparkles',
          earnedDate: '2026-08-15',
          rarity: 'common',
        },
        {
          id: 'b-clarity',
          name: 'Clarity Champion',
          description: 'Awarded for explaining complex CSS layouts in under 15 minutes',
          icon: 'Flame',
          earnedDate: '2026-09-02',
          rarity: 'rare',
        },
      ],
    },
    createdAt: '2026-06-10T12:00:00Z',
  },
  {
    id: 'user-rahul',
    email: 'rahul.sharma@stanford.edu',
    fullName: 'Rahul Sharma',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    college: 'Stanford University',
    course: 'Electrical Engineering & CS',
    year: 'Junior (3rd Year)',
    location: 'Palo Alto, CA',
    bio: 'Python enthusiast & Systems TA. I love breaking down tricky loop semantics, memory references, and algorithmic complexity with visual mental models.',
    mode: 'both',
    activeMode: 'mentor',
    isOnboarded: true,
    preferredLanguage: 'English',
    learningFormat: 'Code Walkthrough',
    skillsToLearn: [
      {
        id: 's-rust',
        name: 'Rust Systems',
        level: 'Intermediate',
        category: 'Programming',
        verified: false,
      },
    ],
    skillsToTeach: [
      {
        id: 's-python',
        name: 'Python',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Skill Assessment Passed',
        endorsementsCount: 38,
        yearsOrMonthsExperience: '3 years',
      },
      {
        id: 's-algorithms',
        name: 'Algorithm Optimization',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Project Verified',
        endorsementsCount: 22,
      },
    ],
    learningGoals: [],
    availability: {
      status: 'available',
      days: ['Mon', 'Tue', 'Thu', 'Sat', 'Sun'],
      timeSlots: ['2:00 PM - 5:00 PM', '7:00 PM - 11:00 PM'],
      preferredDurationMinutes: 20,
    },
    reputation: {
      score: 96,
      learnersHelped: 28,
      sessionsCount: 34,
      averageRating: 4.92,
      clarityScore: 98,
      accuracyScore: 97,
      consistencyScore: 94,
      badges: [
        {
          id: 'b-top',
          name: 'Top Student Mentor',
          description: 'Completed 25+ verified peer sessions with 95%+ learner recommendation rate',
          icon: 'Award',
          earnedDate: '2026-05-18',
          rarity: 'elite',
        },
        {
          id: 'b-clarity',
          name: 'Clarity Champion',
          description: 'Recognized for highest conceptual clarity ratings in Python',
          icon: 'Zap',
          earnedDate: '2026-07-20',
          rarity: 'rare',
        },
        {
          id: 'b-guide',
          name: 'Community Guide',
          description: 'Actively answered over 40 quick doubt requests in community forums',
          icon: 'BookOpen',
          earnedDate: '2026-08-30',
          rarity: 'common',
        },
      ],
    },
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'user-maya',
    email: 'maya.patel@mit.edu',
    fullName: 'Maya Patel',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    college: 'MIT',
    course: 'Computer Science & AI',
    year: 'Senior (4th Year)',
    location: 'Cambridge, MA',
    bio: 'Full-stack builder and open-source contributor. Specializing in React, TypeScript, and modern state architectures. Happy to pair debug!',
    mode: 'both',
    activeMode: 'mentor',
    isOnboarded: true,
    preferredLanguage: 'English',
    learningFormat: 'Problem Solving',
    skillsToLearn: [],
    skillsToTeach: [
      {
        id: 's-react',
        name: 'React & Next.js',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Skill Assessment Passed',
        endorsementsCount: 45,
      },
      {
        id: 's-ts',
        name: 'TypeScript',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Project Verified',
        endorsementsCount: 31,
      },
    ],
    learningGoals: [],
    availability: {
      status: 'available',
      days: ['Tue', 'Thu', 'Fri'],
      timeSlots: ['3:00 PM - 6:00 PM', '8:00 PM - 10:00 PM'],
      preferredDurationMinutes: 15,
    },
    reputation: {
      score: 95,
      learnersHelped: 31,
      sessionsCount: 40,
      averageRating: 4.88,
      clarityScore: 96,
      accuracyScore: 98,
      consistencyScore: 93,
      badges: [
        {
          id: 'b-top',
          name: 'Top Student Mentor',
          description: 'Consistently top rated mentor in Frontend engineering',
          icon: 'Award',
          earnedDate: '2026-04-10',
          rarity: 'elite',
        },
      ],
    },
    createdAt: '2026-02-15T09:30:00Z',
  },
  {
    id: 'user-alex',
    email: 'alex.rivera@georgiatech.edu',
    fullName: 'Alex Rivera',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    college: 'Georgia Tech',
    course: 'Computer Science',
    year: 'Master Student (1st Year)',
    location: 'Atlanta, GA',
    bio: 'Competitive programmer (ICPC Regionalist) & TA for CS1332. Focus on trees, dynamic programming, and graph traversal intuition.',
    mode: 'both',
    activeMode: 'mentor',
    isOnboarded: true,
    preferredLanguage: 'English',
    learningFormat: 'Problem Solving',
    skillsToLearn: [],
    skillsToTeach: [
      {
        id: 's-dsa',
        name: 'Data Structures & Algorithms',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Skill Assessment Passed',
        endorsementsCount: 52,
      },
      {
        id: 's-cpp',
        name: 'C++ Systems',
        level: 'Advanced',
        category: 'Programming',
        verified: true,
        verifiedMethod: 'Teaching History',
        endorsementsCount: 29,
      },
    ],
    learningGoals: [],
    availability: {
      status: 'available',
      days: ['Wed', 'Thu', 'Sat', 'Sun'],
      timeSlots: ['1:00 PM - 4:00 PM', '7:00 PM - 9:00 PM'],
      preferredDurationMinutes: 30,
    },
    reputation: {
      score: 97,
      learnersHelped: 44,
      sessionsCount: 56,
      averageRating: 4.95,
      clarityScore: 99,
      accuracyScore: 99,
      consistencyScore: 95,
      badges: [
        {
          id: 'b-educator',
          name: 'Community Educator',
          description: 'Helped over 40 individual peers solve algorithmic bottlenecks',
          icon: 'ShieldCheck',
          earnedDate: '2026-06-01',
          rarity: 'elite',
        },
      ],
    },
    createdAt: '2026-01-20T08:00:00Z',
  },
];

export const DEMO_REQUESTS: LearningRequest[] = [
  {
    id: 'req-1',
    learnerId: 'user-ojaswitha',
    learnerName: 'Ojaswitha S.',
    learnerCollege: 'UC Berkeley',
    learnerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    skill: 'Python',
    topic: 'Nested Loops & Grid Coordinates',
    currentLevel: 'Beginner',
    description: "I'm having trouble visualizing matrix coordinates `matrix[row][col]` when nesting for loops in 2D array traversals. Looking for a 15-20 min visual walkthrough.",
    preferredLanguage: 'English',
    durationMinutes: 20,
    availabilityNote: 'Available now for the next 2 hours',
    status: 'open',
    createdAt: '2026-09-23T20:15:00Z',
    aiSuggestedKeywords: ['2D arrays', 'Matrix indexing', 'Iteration complexity', 'Nested range()'],
    tags: ['Python', 'Loops', 'Matrices', 'Beginner'],
  },
  {
    id: 'req-2',
    learnerId: 'user-lucas',
    learnerName: 'Lucas Chen',
    learnerCollege: 'UT Austin',
    learnerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    skill: 'React & Next.js',
    topic: 'useEffect Infinite Loop Prevention',
    currentLevel: 'Intermediate',
    description: 'My component keeps fetching data in an endless loop despite having dependency array items. Need someone to inspect the closure pattern.',
    preferredLanguage: 'English',
    durationMinutes: 10,
    availabilityNote: 'Available immediately',
    status: 'open',
    createdAt: '2026-09-23T21:05:00Z',
    aiSuggestedKeywords: ['Closure capture', 'useCallback memoization', 'Reference equality'],
    tags: ['React', 'Hooks', 'State'],
  },
  {
    id: 'req-3',
    learnerId: 'user-priya',
    learnerName: 'Priya Nair',
    learnerCollege: 'Carnegie Mellon',
    learnerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    skill: 'Data Structures & Algorithms',
    topic: 'Recursion Call Stack in DFS Trees',
    currentLevel: 'Beginner',
    description: 'Stuck tracing how return values bubble back up during post-order binary tree traversal. Would love a quick drawing and step-through.',
    preferredLanguage: 'English',
    durationMinutes: 20,
    availabilityNote: 'Free all evening',
    status: 'open',
    createdAt: '2026-09-23T21:20:00Z',
    aiSuggestedKeywords: ['Call stack frames', 'Base cases', 'Binary Tree DFS'],
    tags: ['DSA', 'Trees', 'Recursion'],
  },
];

export const DEMO_SESSIONS: LearningSession[] = [
  {
    id: 'session-demo-1',
    requestId: 'req-1',
    learnerId: 'user-ojaswitha',
    learnerName: 'Ojaswitha S.',
    learnerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    learnerCollege: 'UC Berkeley',
    mentorId: 'user-rahul',
    mentorName: 'Rahul Sharma',
    mentorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    mentorCollege: 'Stanford University',
    skill: 'Python',
    topic: 'Understanding Nested Loops & 2D Coordinates',
    status: 'active',
    startedAt: '2026-09-23T21:35:00Z',
    durationMinutes: 20,
    isRecording: true,
    recordingConsentLearner: true,
    recordingConsentMentor: true,
    recordingSeconds: 412,
    sharedNotes: `# Session Notes: Python Nested Loops
- Outer loop controls row iteration: for r in range(rows)
- Inner loop controls column iteration: for c in range(cols)
- Common pitfall: swapping row and col indices when indexing matrix[r][c]
- Grid pattern:
  [ (0,0), (0,1), (0,2) ]
  [ (1,0), (1,1), (1,2) ]
- Remember: len(matrix) gives row count; len(matrix[0]) gives column count for rectangular grids.`,
    scratchpadCode: `# Python Matrix Traversal Demo
matrix = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]

rows = len(matrix)
cols = len(matrix[0])

print("Traversing row-by-row:")
for r in range(rows):
    for c in range(cols):
        val = matrix[r][c]
        print(f"Cell ({r},{c}) = {val}")
`,
    chatMessages: [
      {
        id: 'm-1',
        senderId: 'user-rahul',
        senderName: 'Rahul Sharma',
        senderRole: 'mentor',
        text: "Hey Ojaswitha! Welcome to the session. Let's look at 2D array nested loops step by step.",
        timestamp: '21:35',
      },
      {
        id: 'm-2',
        senderId: 'user-ojaswitha',
        senderName: 'Ojaswitha S.',
        senderRole: 'learner',
        text: 'Thanks Rahul! When I run nested loops, I keep getting confused why the inner loop completes all iterations before the outer loop moves by 1.',
        timestamp: '21:36',
      },
      {
        id: 'm-3',
        senderId: 'user-rahul',
        senderName: 'Rahul Sharma',
        senderRole: 'mentor',
        text: 'Think of an analog clock: the minute hand has to do a full 60-minute loop for the hour hand to tick forward just 1 step.',
        timestamp: '21:37',
      },
    ],
    copilotItems: [
      {
        id: 'ai-1',
        type: 'clarification',
        level: 'suggestion',
        confidenceText: 'Quick clarification',
        title: 'Clock Hand Analogy Verified',
        content: 'The clock analogy effectively explains outer vs. inner loop iteration speeds. Consider demonstrating with a 3x3 print grid to reinforce row-first traversal.',
        actionableText: 'Show 3x3 printed coordinate map',
        targetAudience: 'mentor',
        status: 'accepted',
        timestamp: '21:37',
      },
      {
        id: 'ai-2',
        type: 'practice_question',
        level: 'silent',
        confidenceText: 'Suggested practice',
        title: 'Check Concept Mastery',
        content: 'Prompt learner: "If you have a 4x5 matrix, how many total times will the print statement inside the nested loop execute?" (Answer: 20)',
        actionableText: 'Ask 4x5 matrix question',
        targetAudience: 'mentor',
        status: 'active',
        timestamp: '21:39',
      },
    ],
  },
  {
    id: 'session-demo-completed',
    learnerId: 'user-ojaswitha',
    learnerName: 'Ojaswitha S.',
    learnerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    learnerCollege: 'UC Berkeley',
    mentorId: 'user-maya',
    mentorName: 'Maya Patel',
    mentorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    mentorCollege: 'MIT',
    skill: 'React & Next.js',
    topic: 'Mastering useState & Controlled Forms',
    status: 'completed',
    startedAt: '2026-09-21T18:00:00Z',
    endedAt: '2026-09-21T18:25:00Z',
    durationMinutes: 25,
    isRecording: true,
    recordingConsentLearner: true,
    recordingConsentMentor: true,
    recordingSeconds: 1480,
    sharedNotes: 'Learned about immutable state updates, event.target.value handling, and why direct state mutation prevents re-rendering.',
    chatMessages: [],
    copilotItems: [],
    summary: {
      learnedTopics: ['Controlled input components', 'State updater functions: setState(prev => ...)', 'Immutability in React'],
      conceptsCovered: ['One-way data flow', 'Syntactic event binding', 'Preventing unwanted re-renders'],
      difficultTopics: ['Updating nested state objects without mutating the parent reference'],
      keyExplanations: [
        {
          concept: 'Object Spread in setState',
          explanation: 'Always use {...prev, field: value} so React detects a new object memory reference and triggers reconciliation.',
        },
      ],
      practiceQuestions: [
        {
          question: 'How do you handle a form with multiple inputs using a single state object?',
          hint: 'Use computed property names: [e.target.name]: e.target.value',
        },
      ],
      recommendedResources: [
        {
          title: 'React Docs: Updating Objects in State',
          url: 'https://react.dev/learn/updating-objects-in-state',
          type: 'Official Guide',
          reason: 'Clear visual diagrams showing why mutation fails to trigger renders',
        },
      ],
      nextStep: 'Practice building a multi-field signup form with validation errors displayed under each input.',
      timestamps: [
        { time: '04:12', topic: 'Why input value must be paired with onChange' },
        { time: '12:45', topic: 'Functional state updates: prev => ({...prev})' },
        { time: '21:30', topic: 'Preventing premature form submissions on Enter' },
      ],
    },
  },
];

export const DEMO_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    authorId: 'user-rahul',
    authorName: 'Rahul Sharma',
    authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    authorCollege: 'Stanford University',
    badge: 'Top Student Mentor',
    type: 'study_tip',
    title: 'How to never get confused by Python 2D indexing again 📐',
    content: 'Always draw your matrix on paper first! Remember that `matrix[row]` selects the horizontal slice, and `[col]` points to the vertical item in that slice. Row comes before Column, just like RC Cola!',
    skillTag: 'Python',
    likes: 38,
    likedBy: [],
    repliesCount: 6,
    createdAt: '2026-09-22T14:30:00Z',
  },
  {
    id: 'post-2',
    authorId: 'user-ojaswitha',
    authorName: 'Ojaswitha S.',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    authorCollege: 'UC Berkeley',
    badge: 'Rising Mentor',
    type: 'achievement',
    title: 'Passed my first Peer Teaching Milestone: 10 Sessions Completed! 🎉',
    content: 'Just finished my 10th peer session teaching responsive CSS Grid and Flexbox tricks. Huge thanks to everyone who joined and gave feedback. The reputation score jumped to 88!',
    skillTag: 'HTML & Modern CSS',
    likes: 47,
    likedBy: [],
    repliesCount: 9,
    createdAt: '2026-09-22T19:00:00Z',
  },
  {
    id: 'post-3',
    authorId: 'user-alex',
    authorName: 'Alex Rivera',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    authorCollege: 'Georgia Tech',
    badge: 'Community Educator',
    type: 'resource',
    title: 'Visual Graph Traversal Cheat Sheet (BFS vs DFS)',
    content: 'Created an open interactive guide comparing when to use BFS (shortest path in unweighted graphs) vs DFS (cycle detection, topological sorting, connected components). Free for anyone studying for midterm rounds!',
    skillTag: 'Data Structures & Algorithms',
    likes: 62,
    likedBy: [],
    repliesCount: 14,
    createdAt: '2026-09-20T10:15:00Z',
  },
];

export const DEMO_RESOURCES: ResourceItem[] = [
  {
    id: 'res-1',
    title: 'Interactive Python Loop Visualizer',
    description: 'Step-by-step code animator showing memory frames and variable values per loop iteration.',
    skill: 'Python',
    topic: 'Loops & Iterations',
    level: 'Beginner',
    type: 'Cheatsheet',
    url: 'https://pythontutor.com',
    sharedBy: 'Rahul Sharma',
    likes: 54,
    aiTags: ['Visualization', 'Memory Tracing', 'Beginner Friendly'],
  },
  {
    id: 'res-2',
    title: 'React Hooks Dependency Array Common Bugs',
    description: 'Curated breakdown of stale closures, infinite fetches, and proper use of useRef.',
    skill: 'React & Next.js',
    topic: 'useEffect & Hooks',
    level: 'Intermediate',
    type: 'Article',
    url: 'https://overreacted.io/a-complete-guide-to-useeffect/',
    sharedBy: 'Maya Patel',
    likes: 89,
    aiTags: ['Hooks', 'Closures', 'Advanced React'],
  },
  {
    id: 'res-3',
    title: 'Blind 75 Curated Algorithm Roadmap with Explanations',
    description: 'Structured peer-reviewed problem set categorized by pattern (sliding window, two pointers, fast & slow).',
    skill: 'Data Structures & Algorithms',
    topic: 'Problem Solving',
    level: 'Intermediate',
    type: 'Practice Problems',
    url: 'https://leetcode.com',
    sharedBy: 'Alex Rivera',
    likes: 120,
    aiTags: ['LeetCode', 'Interview Prep', 'Patterns'],
  },
];
