import React, { useState } from 'react';
import {
  Sparkles,
  BookOpen,
  AlertTriangle,
  Lightbulb,
  HelpCircle,
  Link,
  ArrowRight,
  Clock,
  Download,
  CheckCircle2,
} from 'lucide-react';
import { Modal } from '../common/Modal';
import { SessionSummary } from '../../types';

interface SessionSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary: SessionSummary | null;
  sessionTopic: string;
  mentorName: string;
}

export const SessionSummaryModal: React.FC<SessionSummaryModalProps> = ({
  isOpen,
  onClose,
  summary,
  sessionTopic,
  mentorName,
}) => {
  const [revealedHints, setRevealedHints] = useState<Record<number, boolean>>({});
  const [savedSuccess, setSavedSuccess] = useState(false);

  if (!summary) return null;

  const toggleHint = (idx: number) => {
    setRevealedHints((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const handleExport = () => {
    const markdown = `# AI Session Summary: ${sessionTopic}
Mentor: ${mentorName}

## What You Learned
${summary.learnedTopics.map((t) => `- ${t}`).join('\n')}

## Concepts Covered
${summary.conceptsCovered.map((c) => `- ${c}`).join('\n')}

## Areas of Difficulty
${summary.difficultTopics.map((d) => `- ${d}`).join('\n')}

## Key Explanations
${summary.keyExplanations.map((e) => `### ${e.concept}\n${e.explanation}`).join('\n\n')}

## Practice Questions
${summary.practiceQuestions.map((q, i) => `${i + 1}. ${q.question}\n   *Hint: ${q.hint}*`).join('\n\n')}

## Next Step
${summary.nextStep}
`;
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PeerLoop-Summary-${sessionTopic.replace(/\s+/g, '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 2000);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="AI Session Summary & Knowledge Synthesis"
      subtitle={`Generated by Gemini for "${sessionTopic}" with ${mentorName}`}
      maxWidth="2xl"
    >
      <div className="space-y-5">
        {/* Top Badges / Next Step Banner */}
        <div className="p-4 rounded-xl bg-gradient-to-r from-indigo-950/70 to-slate-900 border border-indigo-500/30">
          <div className="flex items-center gap-2 text-indigo-400 text-xs font-bold uppercase tracking-wider mb-1">
            <Sparkles className="w-4 h-4" />
            <span>Recommended Next Learning Step</span>
          </div>
          <p className="text-sm font-semibold text-white">{summary.nextStep}</p>
        </div>

        {/* Timestamps Jump List */}
        {summary.timestamps && summary.timestamps.length > 0 && (
          <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 text-indigo-400" />
              <span>Session Milestones & Timestamps</span>
            </h4>
            <div className="flex flex-wrap gap-2">
              {summary.timestamps.map((ts, idx) => (
                <div
                  key={idx}
                  className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-slate-900 border border-slate-800 text-xs text-slate-300"
                >
                  <span className="font-mono text-indigo-400 font-semibold">{ts.time}</span>
                  <span>{ts.topic}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 2-Column Grid: What You Learned & Difficulties */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* What you learned */}
          <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/20 space-y-2">
            <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4" />
              <span>What You Mastered</span>
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-300">
              {summary.learnedTopics.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-emerald-400 font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Areas of difficulty */}
          <div className="p-4 rounded-xl bg-amber-950/20 border border-amber-500/20 space-y-2">
            <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
              <AlertTriangle className="w-4 h-4" />
              <span>Areas of Hesitation / Difficulty</span>
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-300">
              {summary.difficultTopics.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-amber-400 font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Key Explanations */}
        {summary.keyExplanations && summary.keyExplanations.length > 0 && (
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Lightbulb className="w-4 h-4 text-cyan-400" />
              <span>Key Explanations & Mental Models</span>
            </h4>
            <div className="space-y-2">
              {summary.keyExplanations.map((exp, idx) => (
                <div key={idx} className="p-3 rounded-lg bg-slate-950 border border-slate-800">
                  <p className="text-xs font-bold text-cyan-300">{exp.concept}</p>
                  <p className="text-xs text-slate-300 mt-1 leading-relaxed">{exp.explanation}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Practice Questions */}
        {summary.practiceQuestions && summary.practiceQuestions.length > 0 && (
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <HelpCircle className="w-4 h-4 text-indigo-400" />
              <span>Practice Questions to Test Retention</span>
            </h4>
            <div className="space-y-2.5">
              {summary.practiceQuestions.map((pq, idx) => (
                <div key={idx} className="p-3 rounded-lg bg-slate-950 border border-slate-800 space-y-1.5">
                  <p className="text-xs font-medium text-white">{pq.question}</p>
                  <div className="flex items-center justify-between pt-1">
                    <button
                      type="button"
                      onClick={() => toggleHint(idx)}
                      className="text-[11px] text-indigo-400 hover:underline"
                    >
                      {revealedHints[idx] ? 'Hide Hint' : 'Show Hint'}
                    </button>
                    {revealedHints[idx] && (
                      <span className="text-[11px] text-slate-400 italic bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                        Hint: {pq.hint}
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommended Resources */}
        {summary.recommendedResources && summary.recommendedResources.length > 0 && (
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Link className="w-4 h-4 text-emerald-400" />
              <span>Recommended Study Materials</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {summary.recommendedResources.map((res, idx) => (
                <a
                  key={idx}
                  href={res.url}
                  target="_blank"
                  rel="noreferrer"
                  className="p-3 rounded-lg bg-slate-950 hover:bg-slate-850 border border-slate-800 hover:border-indigo-500/50 transition-all block group"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-indigo-300 group-hover:text-indigo-200">
                      {res.title}
                    </span>
                    <span className="text-[10px] text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded">
                      {res.type}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">{res.reason}</p>
                </a>
              ))}
            </div>
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-4 border-t border-slate-800">
          <button
            type="button"
            onClick={handleExport}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{savedSuccess ? 'Downloaded!' : 'Export Markdown'}</span>
          </button>

          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-md shadow-indigo-600/25"
          >
            Done
          </button>
        </div>
      </div>
    </Modal>
  );
};
